/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface ZenitButton {
        /**
          * Whether the button should not be clickable.
         */
        "disabled": boolean;
        /**
          * Whether the button should have a 1:1 aspect ratio. This is useful for icon buttons.
         */
        "icon": boolean;
        /**
          * Whether to use primary styling for this button.
         */
        "primary": boolean;
        /**
          * Whether to display the button as a rounded rectangle instead of a pill.
         */
        "rounded": boolean;
        /**
          * Whether to use transparent/tertiary styling for this button.
         */
        "transparent": boolean;
    }
    interface ZenitCheckbox {
        /**
          * Whether the button should not be clickable.
         */
        "disabled": boolean;
        /**
          * Whether to allow "click" actions to switch to the intermediate/mixed state.
         */
        "tristate": boolean;
        /**
          * Whether the box is checked. If it has an indeterminate value, then use "mixed".
         */
        "value": "on" | "off" | "mixed";
    }
    interface ZenitSwitch {
        /**
          * Whether the switch is on (true) or off (false).
         */
        "checked": boolean;
        /**
          * Whether the button should not be clickable.
         */
        "disabled": boolean;
    }
    interface ZenitTextbox {
        /**
          * Whether the input is disabled
         */
        "disabled": boolean;
        /**
          * Label for the input
         */
        "label"?: string;
        /**
          * Placeholder for the input
         */
        "placeholder": string;
        /**
          * Whether the input is required
         */
        "required": boolean;
        /**
          * Type for the input
         */
        "type": 'text' | 'password' | 'search' | 'url' | 'email' | 'tel';
        /**
          * Value for the input
         */
        "value": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLZenitButtonElement extends Components.ZenitButton, HTMLStencilElement {
    }
    var HTMLZenitButtonElement: {
        prototype: HTMLZenitButtonElement;
        new (): HTMLZenitButtonElement;
    };
    interface HTMLZenitCheckboxElement extends Components.ZenitCheckbox, HTMLStencilElement {
    }
    var HTMLZenitCheckboxElement: {
        prototype: HTMLZenitCheckboxElement;
        new (): HTMLZenitCheckboxElement;
    };
    interface HTMLZenitSwitchElement extends Components.ZenitSwitch, HTMLStencilElement {
    }
    var HTMLZenitSwitchElement: {
        prototype: HTMLZenitSwitchElement;
        new (): HTMLZenitSwitchElement;
    };
    interface HTMLZenitTextboxElement extends Components.ZenitTextbox, HTMLStencilElement {
    }
    var HTMLZenitTextboxElement: {
        prototype: HTMLZenitTextboxElement;
        new (): HTMLZenitTextboxElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "zenit-button": HTMLZenitButtonElement;
        "zenit-checkbox": HTMLZenitCheckboxElement;
        "zenit-switch": HTMLZenitSwitchElement;
        "zenit-textbox": HTMLZenitTextboxElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface ZenitButton {
        /**
          * Whether the button should not be clickable.
         */
        "disabled"?: boolean;
        /**
          * Whether the button should have a 1:1 aspect ratio. This is useful for icon buttons.
         */
        "icon"?: boolean;
        /**
          * Whether to use primary styling for this button.
         */
        "primary"?: boolean;
        /**
          * Whether to display the button as a rounded rectangle instead of a pill.
         */
        "rounded"?: boolean;
        /**
          * Whether to use transparent/tertiary styling for this button.
         */
        "transparent"?: boolean;
    }
    interface ZenitCheckbox {
        /**
          * Whether the button should not be clickable.
         */
        "disabled"?: boolean;
        /**
          * Whether to allow "click" actions to switch to the intermediate/mixed state.
         */
        "tristate"?: boolean;
        /**
          * Whether the box is checked. If it has an indeterminate value, then use "mixed".
         */
        "value"?: "on" | "off" | "mixed";
    }
    interface ZenitSwitch {
        /**
          * Whether the switch is on (true) or off (false).
         */
        "checked"?: boolean;
        /**
          * Whether the button should not be clickable.
         */
        "disabled"?: boolean;
    }
    interface ZenitTextbox {
        /**
          * Whether the input is disabled
         */
        "disabled"?: boolean;
        /**
          * Label for the input
         */
        "label"?: string;
        /**
          * Placeholder for the input
         */
        "placeholder"?: string;
        /**
          * Whether the input is required
         */
        "required"?: boolean;
        /**
          * Type for the input
         */
        "type"?: 'text' | 'password' | 'search' | 'url' | 'email' | 'tel';
        /**
          * Value for the input
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "zenit-button": ZenitButton;
        "zenit-checkbox": ZenitCheckbox;
        "zenit-switch": ZenitSwitch;
        "zenit-textbox": ZenitTextbox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "zenit-button": LocalJSX.ZenitButton & JSXBase.HTMLAttributes<HTMLZenitButtonElement>;
            "zenit-checkbox": LocalJSX.ZenitCheckbox & JSXBase.HTMLAttributes<HTMLZenitCheckboxElement>;
            "zenit-switch": LocalJSX.ZenitSwitch & JSXBase.HTMLAttributes<HTMLZenitSwitchElement>;
            "zenit-textbox": LocalJSX.ZenitTextbox & JSXBase.HTMLAttributes<HTMLZenitTextboxElement>;
        }
    }
}
